# -*- mode: ruby -*-
# vi: set ft=ruby :

project = "akilion-chef-server"

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |baseconfig|

  baseconfig.vm.define project do |config|
    
    config.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--cpus", 1]
    end

    config.vm.box = "ubuntu-12.04-akilion01"
    config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box"
    config.vm.hostname = project
    config.vm.synced_folder "../../chef", "/srv/chef"

  end

end
